server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto_rental?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
      timeout: 10000
      expire: 60000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.xzit.rental.entity
  global-config:
    db-config:
      login-delete-field: deleted
encoder:
  ctype:
    strength: 6
    secret: ${random.uuid}
request:
  login-url: /rental/user/login